-- DROP DATABASE
DROP DATABASE IF EXISTS ecommerce_db;

-- CREATE DATABASE
CREATE DATABASE ecommerce_db;

USE ecommerce_db;

CREATE TABLE category (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  category_name VARCHAR(30) NOT NULL
);

CREATE TABLE product (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  product_name VARCHAR(30) NOT NULL,
  price DECIMAL(8,2) NOT NULL,
  stock INT NOT NULL DEFAULT 10,
  categoryId INT,
  FOREIGN KEY (categoryId)
  REFERENCES category(id)
  ON DELETE SET NULL
);



CREATE TABLE tag (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  tag_name VARCHAR(30) NOT NULL
);


CREATE TABLE productTag (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  productId INT,
  FOREIGN KEY (productId)
  REFERENCES product(id)
  ON DELETE SET NULL,
  tagId INT,
  FOREIGN KEY (tagId)
  REFERENCES tag(id)
  ON DELETE SET NULL
);

